#!/usr/bin/env node
/**
 * Regenerates the statistics block in README.md from the dataset.
 *
 *   node scripts/update-readme.mjs           report what would change
 *   node scripts/update-readme.mjs --write   rewrite the block
 *
 * WHY THIS EXISTS
 *
 * The README opened with "140 releases · 19 labs · 28 families" for as long as
 * it took anybody to notice, by which point it was 179 · 21 · 32. A number
 * typed by hand into prose is a number that stops being true the next time the
 * data moves, and this project's whole claim is that its figures are checkable.
 * A README that lies about the size of the dataset undercuts that before a
 * reader reaches anything else.
 *
 * So the block between the markers is generated, and `npm run check` fails if
 * it has drifted — the same shape as every other gate here: the machine
 * notices, not a person remembering.
 *
 * Everything below is COUNTED, never estimated. Where a figure would need a
 * judgement (what "complete" means, say) it is not here.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { canonicalDate } from '../lib/record.mjs';

const WRITE = process.argv.includes('--write');
const FILE = 'README.md';
const START = '<!-- stats:start — generated by scripts/update-readme.mjs, do not edit by hand -->';
const END = '<!-- stats:end -->';

const data = JSON.parse(readFileSync('data/llm-releases.json', 'utf8'));
const milestones = JSON.parse(readFileSync('data/milestones.json', 'utf8')).milestones ?? [];
const R = data.releases;

const n = (x) => x.toLocaleString('en-US');
const pct = (a, b) => `${Math.round((a / b) * 100)}%`;

const labs = new Set(R.map((r) => r.company)).size;
const families = new Set(R.map((r) => r.family)).size;
const verified = R.filter((r) => r.provenance?.status === 'verified').length;
const open = R.filter((r) => r.access?.open_weights).length;
const archived = R.filter((r) => r.sources.every((s) => s.archived_url)).length;
const traced = R.filter((r) => r.evidence && Object.keys(r.evidence).length).length;

const types = {};
for (const r of R) types[r.classification?.primary_type ?? 'language'] = (types[r.classification?.primary_type ?? 'language'] ?? 0) + 1;
const nonLanguage = R.length - (types.language ?? 0);

const dates = R.map(canonicalDate).filter(Boolean).sort();
const span = `${dates[0].slice(0, 4)}–${dates.at(-1).slice(0, 4)}`;
const latest = [...R].sort((a, b) => canonicalDate(b).localeCompare(canonicalDate(a)))[0];

const typeLine = Object.entries(types)
  .filter(([k]) => k !== 'language')
  .sort((a, b) => b[1] - a[1])
  .map(([k, v]) => `${v} ${k.replace(/_/g, ' ')}`)
  .join(' · ');

const block = `${START}

| | |
|---|---|
| **Releases tracked** | **${n(R.length)}** across ${labs} labs and ${families} families, ${span} |
| **Verified** | ${n(verified)} (${pct(verified, R.length)}) — every value they assert traced to a primary source |
| **Facts traced to a source** | ${n(traced)} records carry claim-level evidence |
| **Fully archived** | ${n(archived)} records where every source has a snapshot |
| **Open weights** | ${n(open)} (${pct(open, R.length)}) |
| **Beyond language** | ${n(nonLanguage)} (${pct(nonLanguage, R.length)}) — ${typeLine} |
| **Milestones** | ${milestones.length} dated events that were not model releases |
| **Most recent** | ${latest.model} — ${latest.company}, ${canonicalDate(latest)} |
| **Dataset updated** | ${data.updated} |

<sub>Counted from \`data/llm-releases.json\` by \`scripts/update-readme.mjs\`. Nothing here is estimated; \`npm run check\` fails if this table has drifted from the data.</sub>

${END}`;

const readme = readFileSync(FILE, 'utf8');
const i = readme.indexOf(START);
const j = readme.indexOf(END);
if (i < 0 || j < 0) {
  console.error(`${FILE} has no ${START} … ${END} block — add one first.`);
  process.exit(1);
}
const next = readme.slice(0, i) + block + readme.slice(j + END.length);

if (next === readme) {
  console.log('README statistics are current.');
  process.exit(0);
}
if (!WRITE) {
  console.error('README statistics are STALE — run `npm run readme` to regenerate.\n');
  console.error(block.split('\n').filter((l) => l.startsWith('|')).join('\n'));
  process.exit(1);
}
writeFileSync(FILE, next);
console.log(`wrote ${FILE} — ${R.length} releases, ${labs} labs, ${verified} verified`);
